### ISSUE TITLE
simple_history\object_history.html (Source does not exist)

### ISSUE THREAD

**Issue by dvalero7** [treyhunner/django-simple-history#228] opened 2016-07-21 06:49 UTC
Hi,
I have the next issue, when click in history option in mi admin site.
I think the problem is the template declaration in settings.py, attached my code and logs:
## code

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS':[os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
## logs

TemplateDoesNotExist at /admin/KPIS/base/124/history/

simple_history/object_history.html

Request Method:     GET
Request URL:    http://127.0.0.1:8800/admin/KPIS/base/124/history/
Django Version:     1.9.1
Exception Type:     TemplateDoesNotExist
Exception Value:    

simple_history/object_history.html

Exception Location:     C:\Python34\lib\site-packages\django-1.9.1-py3.4.egg\django\template\loader.py in render_to_string, line 137
Python Executable:  C:\Python34\python.exe
Python Version:     3.4.4

**Comment by joshvillbrandt** [comment] 2017-11-29 18:31
Did you add "simple_history" to `INSTALLED_APPS`? Maybe #69 will help.

**Comment by joshvillbrandt** [comment] 2017-11-29 19:47
I'm currently having this issue as well. I've tried reinstalling Django and django-simple-history using `sudo pip install` and with `pip install` inside of a virtualenv. Using the latest version of both repos which are Django==1.11.7 and django-simple-history==1.9.0.

My temporary hack is to use `python setup.py develop` (to force django-simple-history to install as a directory and not an egg) and to modify the TEMPLATES setting in `settings.py` to include the template files directly.

```python
# from this:
TEMPLATES = [
    {
        ...
        'DIRS': [],
        ...
    },
]

# to this:
TEMPLATES = [
    {
        ...
        'DIRS': [
            os.path.join(BASE_DIR, 'env', 'lib', 'python2.7', 'site-packages', 'django_simple_history-1.9.0-py2.7.egg', 'simple_history')
        ],
        ...
    },
]
```

This does not seem right though (the [docs](https://django-simple-history.readthedocs.io/en/latest/usage.html#install) make it seem like should not have to do anything) so I'd love for someone to show me the error in my process.

Thanks!

**Comment by macro1** [comment] 2017-11-30 03:56
@joshvillbrandt `sudo` probably does not do what you would expect it to do within a virtualenv. Check what `sudo which python` or `sudo which pip` outputs, I would be really surprised if it's installing into your virtualenv correctly.

Regarding possible issues with the package, our tests have run against Django 1.11.7 in the [latest build on master](https://travis-ci.org/treyhunner/django-simple-history/jobs/307048825) and our tests that run with newer versions of Django are very minimal and can be found here:
https://github.com/treyhunner/django-simple-history/blob/1.9.0/runtests.py#L46

I believe there was a brief time the package was misconfigured, and the templates were not packaged correctly, but I am pretty sure the latest version is functioning correctly. You can find the template path [in the manifest](https://github.com/treyhunner/django-simple-history/blob/1.9.0/MANIFEST.in), and if you run `python setup.py build`, you will find the templates in the correct location in the build folder.

If you still believe there may be a legitimate issue with the project, please put a demo Django project together and push it to Github, I will clone it down and see if I can reproduce it.

**Comment by joshvillbrandt** [comment] 2017-12-01 20:24
Hey, @macro1! Thanks for the quick reply.

A fresh install seems to work now! I wonder what the root problem was. :/ A slight change is that I'm using Django==1.11.7 now because of another plugin, but I'm not sure that was it.

(By the way, I wasn't trying to use sudo inside of virtualenv. I had tried to separate approach sudo + not virtualenv and not sudo + virtualenv. Sorry for not being clear in my previous message.)

Thanks again!

**Comment by joshvillbrandt** [comment] 2017-12-01 20:25
Oh.. I can't close this myself? Well anyway, this can be closed.

**Closed** 2018-04-06 22:58 UTC

**Comment by filipnovotny** [comment] 2018-05-20 09:34
I don't think this issue should be closed.
It seems to me that the problem comes from django looking for the template in ./django/contrib/admin/templates/admin/simple_history/object_history.html
when in fact it is installed in:
./django/contrib/admin/templates/admin/object_history.html

**Comment by bussiere** [comment] 2019-03-22 14:06
Same issue here : 

TemplateDoesNotExist at /admin/Transport/stationt/1275/history/

simple_history/object_history.html

**Comment by jorguerra** [comment] 2021-08-02 15:38
I have the same issue, how this can be solved?¡
