### ISSUE TITLE
Model history list missing in Django-admin panel

### ISSUE THREAD

**Issue by r0b1n1sl4m** [treyhunner/django-simple-history#503] opened 2018-12-12 19:43 UTC
Right now the only way to check an instance history is by clicking in history button from model instance single view in from in Django-admin. I couldn't find a way to list all history changes for a specific model, there is also no way to check deleted instance history form the Django-admin.

I'm hoping if is there any way to see the list of history for a specific model from Django-admin and revert deleted instance.

Not sure if it's a bug or just a missing feature so I'm sending some of my admin panel screenshots here:
![image](https://user-images.githubusercontent.com/6296015/49894444-21b76d80-fe78-11e8-84ca-03192e72ebb3.png)
![image](https://user-images.githubusercontent.com/6296015/49894474-33007a00-fe78-11e8-920d-69ac5a6a9daa.png)

**Comment by rossmechanic** [comment] 2018-12-12 20:13
Hey @r0b1n1sl4m it's not a bug – Just a missing feature as described in #72. It's something people have wanted for awhile but haven't gotten two. We've had it on our roadmap but have a few more things we want to clean up before getting there. If you'd like to submit a PR, I'd be to accept it. Going to close this since it's a duplicate of #72.

**Closed by rossmechanic** 2018-12-12 20:13 UTC
