### ISSUE TITLE
django-simple-history middleware issue

### ISSUE THREAD

**Issue by krishna31** [treyhunner/django-simple-history#369] opened 2018-04-11 12:07 UTC
Traceback:

Traceback (most recent call last):
  File "/home/krishna/app/venv/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/home/krishna/app/venv/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 147, in inner_run
    handler = self.get_handler(*args, **options)
  File "/home/krishna/app/venv/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/runserver.py", line 27, in get_handler
    handler = super(Command, self).get_handler(*args, **options)
  File "/home/krishna/app/venv/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 68, in get_handler
    return get_internal_wsgi_application()
  File "/home/krishna/app/venv/local/lib/python2.7/site-packages/django/core/servers/basehttp.py", line 47, in get_internal_wsgi_application
    return import_string(app_path)
  File "/home/krishna/app/venv/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 20, in import_string
    module = import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/krishna/app/underwrite_assistant/underwrite_assistant/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/krishna/app/venv/local/lib/python2.7/site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
    return WSGIHandler()
  File "/home/krishna/app/venv/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 151, in __init__
    self.load_middleware()
  File "/home/krishna/app/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 58, in load_middleware
    mw_instance = mw_class()
TypeError: __init__() takes exactly 2 arguments (1 given)

**Comment by rossmechanic** [comment] 2018-04-11 14:32
Hey @krishna31 can you give me some more details about what's going on here so I can reproduce it? What version of Django are you using? What version of simple history? When does this error get thrown? Thanks.

**Comment by daniell** [comment] 2018-04-24 08:57
I'm pretty sure this happens in Django 1.11 when using the MIDDLEWARE_CLASSES setting instead of the new MIDDLEWARE setting. Django expects old style middleware and doesn't pass in the get_response parameter. Renaming the setting fixes the issue.

**Comment by iamanikeev** [comment] 2018-05-02 14:32
I still think this is a compatibility bug, since Django supports both styles of middleware. If for some reason you have to keep old style (f.e. some of the libraries you use haven't updated their middlewares yet), you cannot upgrade to 2.0 version.

**Comment by rossmechanic** [comment] 2018-05-02 14:58
Ah, @iamanikeev you're right. There were issues that the middleware wasn't working for Django>=1.10 but that was probably for people using the new-style middleware. I fixed that in #364 but didn't make it backwards compatible for people using the old-style middleware, which is still available in Django 1.11. If you use django-simple-history==1.9.1, then the old middleware will work. Feel free to submit a patch to have the old middleware work with the current master branch

**Comment by iamanikeev** [comment] 2018-05-02 15:17
OK, I'll create a PR.

**Comment by rossmechanic** [comment] 2018-06-01 17:27
@iamanikeev any update on PR?

**Comment by iamanikeev** [comment] 2018-06-02 15:54
Hi! sorry, I've got stuck on it.. made the changes to middleware, and couldn't fix tests. Will give it another try tomorrow.

**Comment by iamanikeev** [comment] 2018-06-02 20:35
@rossmechanic Done! here is the PR: https://github.com/treyhunner/django-simple-history/pull/403

**Comment by rossmechanic** [comment] 2018-06-04 14:01
Closed by #403

**Closed by rossmechanic** 2018-06-04 14:01 UTC
Labels: bug
