### ISSUE TITLE
Override history field

### ISSUE THREAD

**Issue by Stahet** [treyhunner/django-simple-history#429] opened 2018-09-01 16:45 UTC
**Description**
I have a history field in a Base class that every model in my project inherit from.

There are some models that I want to exclude specific fields from history. Overriding history to exclude some fields in Child model it's not working properly.

**Example**
```python
from django.db import models
from simple_history.models import HistoricalRecords

class Base(models.Model):
    # Base field 1
    # Base field 2
    # ....
    history = HistoricalRecords(inherit=True)
    
class Child(Base):
    history = HistoricalRecords(exclude_fields=['field1','field2'])
    field1 = models.CharField(max_length=2)
    field2 = models.BooleanField()

```
**Expected behavior**
HistoryChild field1 and field2 should be excluded from migration files.

**Environment**
 - Ubuntu 16.04
 - Django Simple History Version: 2.3.0
 - Django Version: 1.11
 - Database Version:  PostgreSQL 9.6

**Comment by rossmechanic** [comment] 2018-09-20 15:33
Is your Base class an abstract class? The inherit feature is only meant to be used on Abstract models

**Comment by Stahet** [comment] 2018-09-20 15:59
Yes, it is an abstract class

**Comment by rossmechanic** [comment] 2018-12-14 17:44
Just tried this locally and couldn't reproduce. I assume you must have not set `class Meta: abstract=True` on the abstract model. Closing this

**Closed by rossmechanic** 2018-12-14 17:44 UTC

**Comment by ElRoberto538** [comment] 2020-01-30 02:26
I'm having an issue with this as well, is it expected that we can do this? Example Below:

```
class Base(models.Model):
    ...
    history = HistoricalRecords(inherit=True)

    class Meta:
        abstract = True

class Child(Base):
    ...
    history = HistoricalRecords(exclude_fields=['field1', 'field2'])
```

simple_history.exceptions.MultipleRegistrationsError: api.Child registered multiple times for history tracking.
