### ISSUE TITLE
Using django-simple-history to track history of change of specific field of model

### ISSUE THREAD

**Issue by shalinikh** [treyhunner/django-simple-history#199] opened 2015-11-23 12:17 UTC
Hi,

I am using django-simple-history to track history of my_model. 
1. I wish to use it to detect change in only specific fields of my_model.
2. I do not want my_model's all fields replication in history_my_model. I just want that specific field track and addition in history_my_model.

I wish it to get updated whenever i execute .save, .bulk_create or .update.

I did not find any documentations available for this.

**Comment by macro1** [comment] 2015-12-02 04:54
Hello @shalinikh! As you already know simple-history doesn't look at the values being saved at all. It blindly saves a new historical version on every save or delete signal. There is another tool, [Field Tracker](http://django-model-utils.readthedocs.org/en/latest/utilities.html#field-tracker) that would get you closer to what you're looking for.

As it's not something I need right now, I haven't put any work toward seeing how something like that would work with simple-history. At minimum, we could add a way to prevent saving duplicate historical versions. If this is something you would like to see added, feel free to make a pull request.

**Comment by luzfcb** [comment] 2015-12-02 14:47
@macro1 I need to do the opposite. I wish I could exclude some fields to be versioned

something like that

```python
class Article(models.Model):
    content = models.CharField(max_length=200)
    nontrackedfield1 = models.NullBooleanField(default=False, editable=False)
    nontrackedfield2 = models.NullBooleanField(default=False, editable=False)

    history = HistoricalRecords(non_tracked_fields=('nontrackedfield1', 'nontrackedfield2'))
```

I would like to try to implement this, but I still can not understand what is the magic the HistoricalRecords() do to create a HistoricalRecord Model

you have time and patience, you could explain to me how and where that magic happens?

**Comment by macro1** [comment] 2015-12-03 02:13
@luzfcb, we actually had a request for that earlier this year (#165). I'll link the relevant code there so the issues don't get too cluttered.

**Comment by rossmechanic** [comment] 2018-06-21 23:06
Closing this as a dupe of #174

**Closed** 2018-06-29 13:47 UTC
Labels: enhancement
