### ISSUE TITLE
Delete old Historical Records

### ISSUE THREAD

**Issue by cleder** [treyhunner/django-simple-history#198] opened 2015-11-17 16:01 UTC
To keep the history growing too much I'd like to have a function that deletes all historical records older than x days. So the function can be reused in a management command or a celery task

**Comment by robmoorman** [comment] 2016-03-14 11:42
Also the ability to delete old record via the admin would be nice.

**Comment by michael54** [comment] 2016-04-11 02:24
:+1:

**Comment by macro1** [comment] 2016-04-11 03:36
This might go without saying, but doing this with the ORM is pretty easy:

```python
MyModel.history.filter(history_date__lt=timezone.now() - timedelta(days=90)).delete()
```

That should delete all historical records older than 90 days. You could also filter on `history_type` if there was a reason to keep deletions around for audit purposes.

**Comment by nbernardshaw** [comment] 2017-06-05 20:21
If django-simple-history can self-manage by having the ability to delete old history records, that would be very useful.

**Comment by nikechristo** [comment] 2017-06-05 20:23
If django-simple-history can self-manage by having the ability to delete old history records, that would be very useful.

**Comment by rossmechanic** [comment] 2018-12-06 20:30
Dupe of #313

**Closed by rossmechanic** 2018-12-06 20:30 UTC
Labels: enhancement
