### ISSUE TITLE
HistoricalObjectDescriptor throws exception with excluded_fields

### ISSUE THREAD

**Issue by wrvdklooster** [treyhunner/django-simple-history#310] opened 2017-08-17 14:42 UTC
The HistoricalObjectDescriptor throws an exception in the __get__ when used with excluded_fields.

This is caused by passing the values instead of a dict to the constructor of the model.

I created following patch:
```
def __get__(self, instance, owner):
    values = {
        f.attname: getattr(instance, f.attname)
        for f in self.fields_included
    }
    return self.model(**values)
```

So instead of passing the values pass a dict with the values so the excluded_fields get the default value.

**Comment by wrvdklooster** [comment] 2018-05-14 15:59
Any idea when this fix can be merged? We are using our own fork now but prefer to use an official release.

**Comment by rossmechanic** [comment] 2018-05-14 16:53
If you want to submit the fix with some tests, I'd be happy to merge this week. Aiming to get a bunch of these PRs reviewed an merged for an end of May release.

**Comment by wrvdklooster** [comment] 2018-06-06 17:08
Sorry, I was unable to create tests. I just installed version 2.1.0 and could not reproduce there. Installing 2.0 back I could reproduce again.

I do however not see any relation between this issue and the updates in 2.1.0.

Do you have any idea?

**Comment by rossmechanic** [comment] 2018-06-06 17:30
Nothing comes immediately to mind. If you can't reproduce in 2.1.0, that's great! Let me know if you figure out why it was fixed and we can document here. But since you can't reproduce the issue in 2.1.0, do you want to close the issue? Thanks.

**Comment by rossmechanic** [comment] 2018-07-02 20:55
Closing this unless you've run into the issue again.

**Closed** 2018-07-02 20:55 UTC
Labels: bug
