### ISSUE TITLE
Model instances with HistoricalRecords do not have changeReason attribute 

### ISSUE THREAD

**Issue by nicolazilio** [treyhunner/django-simple-history#563] opened 2019-05-20 08:38 UTC
**Describe the bug**

Model instances with HistoricalRecords do not have changeReason attribute 

**Expected behavior**

From ReadTheDocs pages, my understanding is, although I may be wrong, that when HistoricalRecords is added to a model, the model should acquire a `changeReason` attribute that can be used to set the reason for changing a record. For example, for a model like this one

```
class SaCerevisiaeStrain (models.Model):
    name = models.CharField("name", max_length = 255, blank=False)
    history = HistoricalRecords()
```
   
I expect SaCerevisiaeStrain to have a `changeReason` attribute that can be accessed like so `SaCerevisiaeStrain.changeReason`. Yet, I cannot see any such attribute. The history DB table does include a`history_change_reason` column, and I can set a value for it using the `update_change_reason` function.

**Environment (please complete the following information):**
 - OS: Debian 8.11 
 - Django Simple History Version: 2.7.2
 - Django Version: 2.1.8
 - Database Version: MariaDB 10.2.6

**Comment by rossmechanic** [comment] 2019-05-20 13:21
Hi @nicolazilio, that's the expect behavior. `changeReason` isn't a field on the base instance, but if you set it on the base instance before saving, the `changeReason` will be saved on `history_change_reason` on the history table. This is done in this line: https://github.com/treyhunner/django-simple-history/blob/3df2061fb35953e2a59b67c119f2dd1bd57bd971/simple_history/models.py#L472

Thus, you'd have to do the following to set the `changeReason` on `SaCervisiaeStrain`:

```
sa_cervisiae_strain = SaCervisiaeStrain.objects.get(pk=1)
... any changes to the sa_cervisiae_strain object
sa_cervisiae_strain.changeReason = "I wanted to change it"
sa_cervisiae_strain.save()
```

Then, to query the change reason on an object, you'd have to query the history of that object and look for the `history_change_reason`.

Closing this since it's expected behavior tho

**Closed by rossmechanic** 2019-05-20 13:21 UTC

**Comment by nicolazilio** [comment] 2019-05-21 07:35
Great, thanks for the explanation.
