### ISSUE TITLE
excluded_fields doesn't work on register(User) in Django

### ISSUE THREAD

**Issue by slenart** [treyhunner/django-simple-history#628] opened 2020-02-14 15:51 UTC
**Describe the bug**
When `exluced_fields` "exclude" some fields in history's table,
then we expected to see only new entries in the historical table for
changes made not in excluded fields.

**To Reproduce**
Got code:
```
from simple_history import register
from django.contrib.auth.models import User


apply_history_to_User = register(
    User, app='core', excluded_fields = ['password', 'last_login'],
    table_name='auth_historicaluser',
    use_base_model_db=True, inherit=True,
)

# change to `app=__package__`
```

**Expected behavior**
last_login field is excluded so when user log in it should **not**
add any record to history's table, but it's not true.
Every login created a new record in history table and values are same
(Except internal history_date of course and history_id)

**Environment (please complete the following information):**
- Django                          2.2.9
- django-simple-history           2.8.0 
- Database Version: [Mysql 5.7.28]

**Comment by rossmechanic** [comment] 2020-02-14 19:47
@slenart this is expected behavior. The columns are excluded, but django-simple-history functions naively. It creates a new record in the history table every time a save is made, regardless of whether or not fields have changed. There's been a decent amount of discussion about using something like django-dirtyfields to handle this differently, but I haven't had enough time to look into, and neither has anyone in the community. Going to close this since it's expected behavior

**Closed by rossmechanic** 2020-02-14 19:47 UTC
