### ISSUE TITLE
History should not be created when model is not dirty

### ISSUE THREAD

**Issue by kunalgrover05** [treyhunner/django-simple-history#386] opened 2018-05-10 04:32 UTC
If I save the same model multiple times using PUT requests, each time a new History instance is created although there are no diffs. I think there should be a configuration to avoid that.

I also use django-auditlog, and it doesn't capture logs when there is no diff. https://github.com/jjkester/django-auditlog/blob/master/src/auditlog/diff.py#L85

**Comment by rossmechanic** [comment] 2018-07-03 15:46
Duplicate of #302

**Closed by rossmechanic** 2018-07-03 15:46 UTC

**Comment by kunalgrover05** [comment] 2018-07-03 16:11
Thank you @rossmechanic.

Sorry for missing the duplicate issue.
