### ISSUE TITLE
Any call to manage.py will fail if no default database is specified

### ISSUE THREAD

**Issue by CianciuStyles** [treyhunner/django-simple-history#264] opened 2017-01-26 11:18 UTC
I'm working on a Django project which does not have any database configuration until the deployment phase, and while trying to run a manage.py command completely unrelated to the usage of django-simple-history (collectstatic, in my case), I'm getting a KeyError because the library it's trying to access the default database configuration (which is absent at this point, and will be added later on) to build and populate the HistoricalRecords models.

Is there a way to bind this behavior with specific manage.py commands (and not all of them), or to make the calls to manage.py not fail in such a particular case?

**Comment by macro1** [comment] 2017-01-26 22:53
Without a traceback I can't really say. was the only change to the project adding simple history? If you can't provide a traceback, is there any way you could reproduce the issue in a minimal project? That is what I would need to do myself to determine what's going on here.

**Comment by CianciuStyles** [comment] 2017-01-27 14:59
Hello @macro1, thank you for the quick response.

I have managed to solve the issue in my situation by adding a 'default' entry in the DATABASES setting with the 'ENGINE' set to '', to make the continuous integration tool to use Django's built-in dummy database for that particular build step.

If you are still interested in troubleshooting the issue, the issue I was getting is the following:
`$ python manage.py check
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 327, in execute
    django.setup()
  File "C:\Python27\lib\site-packages\django\__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Python27\lib\site-packages\django\apps\registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "C:\Python27\lib\site-packages\django\apps\config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\Users\s.cianciulli\Desktop\django_simple_history_issue_264\issue\models.py", line 8, in <module>
    class MyModelWithHistory(models.Model):
  File "C:\Python27\lib\site-packages\django\db\models\base.py", line 291, in __new__
    new_class._prepare()
  File "C:\Python27\lib\site-packages\django\db\models\base.py", line 341, in _prepare
    signals.class_prepared.send(sender=cls)
  File "C:\Python27\lib\site-packages\django\dispatch\dispatcher.py", line 192, in send
    response = receiver(signal=self, sender=sender, **named)
  File "C:\Python27\lib\site-packages\simple_history\models.py", line 88, in finalize
    history_model = self.create_history_model(sender)
  File "C:\Python27\lib\site-packages\simple_history\models.py", line 123, in create_history_model
    fields = self.copy_fields(model)
  File "C:\Python27\lib\site-packages\simple_history\models.py", line 176, in copy_fields
    transform_field(field)
  File "C:\Python27\lib\site-packages\simple_history\models.py", line 272, in transform_field
    field.__class__ = convert_auto_field(field)
  File "C:\Python27\lib\site-packages\simple_history\models.py", line 298, in convert_auto_field
    if settings.DATABASES[connection]['ENGINE'] in ('django_mongodb_engine',):
KeyError: 'default'
`

I've also setup a minimal Django project which would throw the same issue (and traceback), you can find it at https://github.com/CianciuStyles/django_simple_history_issue_264. Please note the absence of the default key in the DATABASES dict (in the settings.py file), which was the same situation I had before.

**Comment by macro1** [comment] 2017-01-27 19:04
Ah. I had forgotten about the MongoDB feature. Also it appears this is a duplicate of #219.

**Comment by CianciuStyles** [comment] 2017-01-31 10:19
That's correct, they seem to talk about the same issue. If I can do anything to help with this, just let me know.

**Comment by macro1** [comment] 2017-01-31 22:13
As a stop-gap, we can probably add exception handling there to assume non-mongodb if there is no matching connection.

Longer term, we could try to move mongo-db to an explicit flag, or allow a custom PK field definition to be passed in. Custom fields on history models is in the requested features somewhere I think. I'm not sure how hard it would be to add though.

**Comment by admed** [comment] 2017-02-27 09:01
I had some issue trying to build docs using sphinx with automodule:

local/lib/python2.7/site-packages/simple_history/models.py", line 300, in convert_auto_field
    if settings.DATABASES[connection]['ENGINE'] in ('django_mongodb_engine',):
KeyError: 'default'

**Comment by rossmechanic** [comment] 2018-12-14 17:15
Fixed by #432

**Closed by rossmechanic** 2018-12-14 17:15 UTC
